version: '3.8'

services:
  flask-app:
    build: ./web-app
    container_name: flask_app
    ports:
      - "10000:5000"
    environment:
      - MONGO_DBNAME=okaycooldb
      - MONGO_URI=mongodb://admin:secret@mongodb:27017
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_PORT=5000
      - INPUT_DIR=images/input
      - OUTPUT_DIR=images/output
      - ARCHIVE_DIR=images/archive
    env_file:
      - ./web-app/.env
    volumes:
      - ./shared-images:/app/images
      - ./machine-learning-client:/machine-learning-client
    depends_on:
      - mongodb
      - face-redaction-client
  
  mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  
  face-redaction-client:
    build: ./machine-learning-client
    container_name: face_redaction_client
    environment:
      - MONGO_DBNAME=okaycooldb
      - MONGO_URI=mongodb://admin:secret@mongodb:27017
      - INPUT_DIR=images/input
      - OUTPUT_DIR=images/output
      - ARCHIVE_DIR=images/archive
      - POLL_INTERVAL=5
    env_file:
      - ./machine-learning-client/.env
    volumes:
      - ./shared-images:/app/images
      - ./machine-learning-client:/machine-learning-client
    depends_on:
      - mongodb

volumes:
  mongo-data:
  shared-images:

networks:
  app-network:
    driver: bridge