name: Machine Learning Client CI

on:
  push:
    branches: [ main ]
    paths:
      - 'machine-learning-client/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'machine-learning-client/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./machine-learning-client

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx libglib2.0-0
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev --system
    
    - name: Lint with pylint
      run: |
        pylint client.py
    
    - name: Format check with black
      run: |
        black --check .
    
    - name: Test with pytest
      run: |
        pytest --cov=client test_client.py
    
    - name: Check code coverage
      run: |
        pytest --cov=client --cov-report=term-missing --cov-fail-under=80 test_client.py 