name: Machine Learning Client CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  test-ml-client:
    name: Test Machine Learning Client
    runs-on: ubuntu-latest
    timeout-minutes: 5

    defaults:
      run:
        working-directory: machine-learning-client

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python, pipenv and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Turn on 'editable' mode
        run: pipenv install -e .

      - name: Install pytest
        run: pipenv install pytest

      - name: Show venv location (optional debug)
        run: pipenv --venv

      - name: Run Tests
        run: pipenv run pytest tests/
